### ISSUE TITLE
Hiding joins/parts breaks layout

### ISSUE THREAD

**Issue by ghost** [erming/shout#233]
When the first message in the chat message list is hidden (via settings by disabling parts/joins etc) it breaks certain formatting.

For example when the first message in the list is a `join` and you have joins disabled and the "Show More" button is showing, because the first message in the list has `display: none` set, the indentation is also hidden and the "Show More" button overlays the content.
![image](https://cloud.githubusercontent.com/assets/7449105/4605763/346d5c8a-51f9-11e4-997b-4a3b46ea56b2.png)

The culprit CSS is:

``` css
#chat .show-more.show + .messages .msg:first-child {
    padding-top: 47px !important;
}
#chat.hide-join .join span, #chat.hide-mode .mode span, #chat.hide-motd .motd span, #chat.hide-nick .nick span, #chat.hide-part .part span, #chat.hide-quit .quit {
    display: none !important;
}
```
